### ISSUE TITLE
As of Rust 1.22.0, the `?` operator can only be used in a function that returns `Result` or `Option`

### ISSUE THREAD

**Issue by Miserlou** [hniksic/rust-subprocess#13]
Using the examples in the documentation causes:

```
error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `std::ops::Try`)
```

I think this is due to behavior change in `1.22.0`+.

**Comment by hniksic** [comment]
The Examples section of the `README` already documents that the code needs to be inside a function that returns `Result` (or `?` replaced with `unwrap` or equivalent):

> Note: these examples use the `?` operator to show the result. If you are pasting them in a function that doesn't return a `Result`, such as `main`, simply replace `X?` with `X.expect("failed to execute")`, or with an appropriate pattern match.

Are there examples where this would fail to apply?

> I think this is due to behavior change in `1.22.0`+.

The `?` operator required the function to return `Result` since it was introduced, and Rust programmers are expected to be aware of that.

**Comment by hniksic** [comment]
@Miserlou Can you clarify the issue you are having with the documentation?

**Comment by hniksic** [comment]
Closing due to lack of feedback by the reporter
