### ISSUE TITLE
Update winapi Dependency!

### ISSUE THREAD

**Issue by Miserlou** [hniksic/rust-subprocess#17]
Hello!

I'm trying to get my application which uses `rust-subprocess` into Debian! To do that, we're going to need to update this package to use newer subdependencies.

Can you bump up `winapi` for this project so that the downstream maintainers can use the latest packages?

Thanks!
Rich

Related: https://github.com/Miserlou/Loop/issues/36

**Comment by kpcyrd** [comment]
For the record, the crossbeam dependency is outdated as well :)

**Comment by hniksic** [comment]
Thanks for the effort! I've now used `cargo upgrade` (from [`cargo-edit`](https://github.com/killercup/cargo-edit)) to upgrade all the dependencies. The win32 code required changes due to incompatible changes in later versions of `winapi` and `crossbeam`. I've also completely removed dependency to `kernel32` and moved from `crossbeam` to the smaller `crossbeam-utils`.

Please let me know if this fixes the issue.
