### ISSUE TITLE
Quoted strings on Windows adds additional quotes

### ISSUE THREAD

**Issue by jonathandturner** [hniksic/rust-subprocess#27]
I'm noticing that subprocess is doing a bit of extra work processing the arguments, and while helpful, it seems like it's not allowing me to encode certain types of calls.

In Windows, for example, there is a difference between: 

> echo foo

and 

> echo "foo"

The latter of these doesn't seem be expressible in subprocess. If I add an argument that is `"foo"`, subprocess will create a second set of quotations around the first, and then escape the first.  This isn't what you want.  If the quotes are at the outside and not inside, I don't believe you want to escape them.

**Comment by hniksic** [comment]
Can you please provide a minimal example showing how you are invoking `subprocess`, along with the expected and observed output? For example, on Linux the following program:

```rust
extern crate subprocess;

use subprocess::{Exec};

fn main() {
    Exec::cmd("echo").arg("foo").join().unwrap();
    Exec::cmd("echo").arg("\"foo\"").join().unwrap();
}
```

prints `foo` and `"foo"` on separate lines.

**Comment by jonathandturner** [comment]
@hniksic - this fix specifically is for Windows. You can try the What you would want is for it to print `foo` and `"foo"`, but (at least, before the PR), it would escape the quotes when passed to echo.

```rust
use subprocess::{Exec};

fn main() {
    Exec::shell("echo").arg("foo").join().unwrap();
    Exec::shell("echo").arg("\"foo\"").join().unwrap();
}
```

Prints:

```
foo
"\"foo\""
```

**Comment by jonathandturner** [comment]
Here's the same program after the PR:

```
foo
"foo"
```

**Comment by hniksic** [comment]
What happens if you start a program other than `echo`? For example, try the `just-echo` program provided with `subprocess` - it simply prints its first argument without any processing. (You could easily write an equivalent C program.)

As far as I can tell, the Windows `echo` utility is interpreting its command line in a non-standard way. For example, using `just-echo` from an ordinary `cmd` doesn't differentiate between `foo` and `"foo"` (as expected):

```
hniksic@DESKTOP-J473IK8 C:\Users\hniksic\rust\subprocess\target\release
> just-echo foo
foo
hniksic@DESKTOP-J473IK8 C:\Users\hniksic\rust\subprocess\target\release
> just-echo "foo"
foo
```
And this is an important feature because it allows one to write `just-echo "foo bar"` and have the string interpreted as a **single** argument `foo bar`, without quotes.

However, `echo` behaves differently:

```
hniksic@DESKTOP-J473IK8 C:\Users\hniksic\rust\subprocess\target\release
> echo foo
foo

hniksic@DESKTOP-J473IK8 C:\Users\hniksic\rust\subprocess\target\release
> echo "foo"
"foo"
```

I think there is no way for `subprocess` to satisfy both Windows `echo` and all other programs. The current quoting algorithm is taken from [here](https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/). As far as I can tell, a very similar algorithm is used by the [Rust stdlib](https://github.com/rust-lang/rust/blob/a73ecb3d9c432f8f53117b1a6b6c209dc802dee7/src/libstd/sys/windows/process.rs#L457)

**Comment by jonathandturner** [comment]
The Windows `echo` is just one popular commandline utility that works this way.  Here's another example:

```rust
    let sh = Exec::shell("git")
        .arg("commit")
        .arg("-a")
        .arg("-m")
        .arg("\"This is a test\"");
```
which attempts to match the commandline:
```
git commit -a -m "This is a test"
```

But if you look at the git log the subprocess version creates vs the commandline, you'll notice that there is a set of quotation marks in the subprocess version, very much like echo.  This is also fixed with the PR.

**Comment by hniksic** [comment]
The last argument *requests* literal quotation marks. The way to match `git commit -a -m "This is a test"` in `subprocess` is to use:

```rust
    let sh = Exec::shell("git")
        .arg("commit")
        .arg("-a")
        .arg("-m")
        .arg("This is a test");
```

Normally the whole *point* of a library like `subprocess` is that it treats arguments as separate entities and takes care of quoting for you. `std::process` works the same way in this regard.

The fix in your PR is incorrect because it doesn't allow you to pass literal double quotes to `git` (and other processes) when you need them. A lot of confusion is caused by the fact that the Windows `echo` command really does work differently from normal programs - as you can easily test using `just-echo` or any C program that prints or inspects `argv`.

**Comment by wycats** [comment]
@hniksic What do you think about adding a newtype like `raw` or `bare` that would say "please don't add any quotes to this:

```
use subprocess::{Exec, raw};

fn main() {
    Exec::shell("echo").arg("foo").join().unwrap();
    Exec::shell("echo").arg("\"foo\"").join().unwrap();
    Exec::shell("echo").arg(raw("\"foo\"")).join().unwrap();
}
```

Output:

```
foo
"\"foo\""
"foo"
```

**Comment by hniksic** [comment]
@wycats Note that `shell` and `arg` are mutually exclusive, so you would either use `Exec::shell("echo foo bar")` or `Exec::cmd("echo").arg("foo").arg("bar")`, but not both.

I am curious as to the intended use case for this feature - why would one pass quoted strings to `arg`? If you have quoted strings, you can construct the shell command-line yourself. The concept of a "quoted" string is dependent not only on the operating system, but also on the shell being used. It requires the crate user to perform correct quoting, and failure leaves the application vulnerable to code injection attacks.

**Comment by hniksic** [comment]
I am closing this issue, as the crate works correctly for the provided use cases. Analysis in [this comment](https://github.com/hniksic/rust-subprocess/issues/27#issuecomment-500725992).

**Comment by dbanty** [comment]
Sorry to revive such an old thread, but I've bumped into this issue and it's not clear to me how to resolve it. Basically, users can provide strings of commands that they want to execute in a config file. I'm trying to execute those commands with `Exec::shell`, which works fine on unix-ish systems, but fails on Windows. In particular, running something like `git commit -m "chore: Prepare release"` is very common.

What's the correct way to solve this?

**Comment by hniksic** [comment]
@dbanty Can you please specify exactly how you are using `subprocess` to run the git command?

**Comment by dbanty** [comment]
`let status = Exec::shell(command).join()?;` where `command` is a string that comes from an input file.

More context, in case you're curious, this is for [Knope](https://knope.tech) which lets folks automate some workflow stuff. Configuration is done in TOML, and a typical workflow looks like:

```toml
[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\" && git push"

[workflows.steps.variables]
"$version" = "Version"

[[workflows.steps]]
type = "Release"
```

Where `PrepareRelease` updates some files, `Command` runs an arbitrary command, optionally with some variable substitution, and `Release` tags or creates a GitHub release, depending on config.
