### ISSUE TITLE
Allow mutable invocation

### ISSUE THREAD

**Issue by alerque** [hniksic/rust-subprocess#38]
I'm having trouble organizing invocations of Exec without a lot of unnecessary code. Take for example:

```rust
let process = Exec::cmd("make").arg("all");
process.join()?;
```

Simple enough, but adding logic to optionally add something to this EXEC before running it is not easy. This works:

```rust
let process = Exec::cmd("make");
let process = process.env("DEBUG", "true");
let process = process.arg("all");
process.join()?;
```

But besides the unnecessary variable shadowing it is hard to wrap in any kind of conditional. Not this doesn't work:

```rust
let process = Exec::cmd("make");
if config.debug {
    let process = process.env("DEBUG", "true");
}
let process = process.arg("all");
process.join()?;
```

If the `Exec` stuct could be mutable, one could do something like this:

```rust
let mut process = Exec::cmd("make");
if config.debug {
    process.env("DEBUG", "true");
}
process.arg("all");
process.join()?;
```

Alternatively some way to introduce closures into the invocation that could decide whether or not to add arguments/envs could be another solution.

**Comment by hniksic** [comment]
> `let process = Exec::cmd("make");`
> `let process = process.env("DEBUG", "true");`
> `let process = process.arg("all");`
> `process.join()?;`

Note that one can write the above without shadowing variables:

```rust
Exec::cmd("make")
    .env("DEBUG", "true")
    .arg("all")
    .join()?;
```

> it is hard to wrap in any kind of conditional. [...] If the `Exec` stuct could be mutable, one could do something like this:

The `Exec` struct *can* be mutable, you just need an explicit assignment to mutate it:

```rust
let mut process = Exec::cmd("make");
if config.debug {
    process = process.env("DEBUG", "true");
}
process = process.arg("all");
process.join()?;
```

**Comment by alerque** [comment]
> Note that one can write the above without shadowing variables:

Thanks for the tip. I am aware of that style since it's the primary thing that's documented for this crate, and it works well if you know everything up front. It doesn't have any way (that I understand) to hook in and conditionally modify the Exec though, hence I wrote out the long form style looking for a way to mutate it.

> The Exec struct can be mutable, you just need an explicit assignment to mutate it:

Again, thanks. This is better code than what I was coming up with. However correct me if I'm wrong but this is just Rust syntax sugar — the total contents of the variable is being swapped out for a new struct each time, no? Maybe what I meant was "interior mutability". I'm pretty new to Rust so excuse me if this isn't the right term either. It seems like there should be a lighter weight way of modifying the Exec without completing generating a new one at each step.

If that's not the case and my understanding of Rust is just too limited feel free to close this. Thanks again for the feedback.

**Comment by hniksic** [comment]
> Again, thanks. This is better code than what I was coming up with. However correct me if I'm wrong but this is just Rust syntax sugar — the total contents of the variable is being swapped out for a new struct each time, no?

It's not really sugar (because assignment *is* the way to modify the variable, rather than a sugarcoating of more basic functionality), but your understanding is mostly correct. I say mostly because I'd like to point out that there is no "new struct", at least not in the sense of a new and old one ever existing in parallel. Since functions like `Exec::arg()` and `Exec::env()` *consume* self, there is only one struct that goes around. Without optimization, that struct would be moved to the function (with just a bitwise copy of fixed size known at compile time), modified inside the function, and then moved back to the caller. But since copy/move elision is a thing in both C++ and Rust, I would expect LLVM to eliminate the moves and generate the exact same code as if the struct were modified in-place. And even if the compiler isn't smart enough to do that, a bitwise of fixed size is extremely efficient and is dwarfed by the cost of actually running the subprocess by several orders of magnitude.

> Maybe what I meant was "interior mutability"

Interior mutability is a different concept: that's when you change the state an object inside a function that accepts `&self`, as opposed to `&mut self`. That is useful when the function has its own ways to enforce the aliasing rules, either through extra-linguistic means guarded with `unsafe` or using the mechanisms provided by the standard library, such as `RefCell` or `Mutex`. It doesn't apply here.

**Comment by hniksic** [comment]
Closing this, as there is no issue here. In summary, there are two ways Rust builders are created: one is to have mutators take and return `&mut self`, and the other to have them consume and return `self`. The advantage of the latter is that it's more obvious how to mutate them outside of a standard chain, as in the case described here. But they also require the final building method to take `&mut self` as well.

In case of `subprocess` it is not possible for e.g. `Exec::join()` to take `&mut self` because `Exec` objects have owneship of streams which they mast pass to the `Popen` object they create. For this to work, they must consume `self`.

**Comment by alerque** [comment]
Roger that, and thanks for the explanation.
