### ISSUE TITLE
Interact with subprocess from a different thread using channels

### ISSUE THREAD

**Issue by martonlanga** [hniksic/rust-subprocess#50]
I'm trying to create something that works kind of like a shell using subprocess. A user enters a command in a webview and this executes the command in a subprocess inside a new thread. I'm trying to communicate with them using channels from the main thread and send messages from there to the subprocesses.
I've managed to make stdout/err work like this but I'm having trouble with stdin.

I've tried a lot of things, here's my current attempt:

```rust
let mut p = Exec::cmd(command)
    .args(&args)
    .cwd(current_dir)
    .stdin(Redirection::Pipe)
    .stdout(Redirection::Pipe)
    .stderr(Redirection::Pipe)
    .popen()?;

let mut stdin = vec![];

while p.poll().is_none() {
    // trying to write stdin (this is not working)
    p.stdin
        .as_ref()
        .unwrap()
        .write_all(&stdin)
        .expect("Failed to write stdin");

    let mut reader = BufReader::new(p.stdout.as_ref().unwrap());
    let mut chunk = [0u8; 64];
    loop {
        let len = reader.read(&mut chunk)?;
        if len == 0 {
            break;
        }
        let chunk = &chunk[..len];

        // send stdout
        let event_result = tauri::event::emit(
            webview,
            "event",
            Some(Payload {
                id: id.clone(),
                chunk,
            }),
        );
        if let Err(err) = event_result {
            println!("Failed to send chunk: {}", err);
        } else {
            println!("Sent chunk");
        };
    }

    // receive stdin message
    let received = receiver.recv();
    if let Ok(message) = received {
        if message == "Exit" {
            println!("Exiting");
            break;
        }

        println!("Message received: {}", message);
        stdin = message.as_bytes().to_owned();
    } else {
        println!("No message or error");
    }
}
```

Please let me know if it's unclear what I'm trying to do. Any help would be appreciated, and thanks for your time!

**Comment by hniksic** [comment]
In what way is writing to the process's stdin "not working"? Does it trigger a panic from `expect`? Does it hang? Or does it fail to produce the desired output from the subprocess?

**Comment by martonlanga** [comment]
The above approach hangs at the line `let len = reader.read(&mut chunk)?;`. So it never breaks out of the loop.

**Comment by hniksic** [comment]
Now I noticed that your `stdin` starts out as empty, so passing it to `write_all()` is no-op. Could it be that you can't read anything because your command is still waiting for you to actually write something?

**Comment by martonlanga** [comment]
Should I only try to write to it if `stdin` is not empty?

Yes, a command that doesn't wait for input works as expected (for example `pwd`). On the other hand, running something that requires the user's input leaves it hanging. Not sure how I should try to re architect the code.

**Comment by hniksic** [comment]
> Should I only try to write to it if `stdin` is not empty?

I am confused by the question. `write_all()` already doesn't try to write if you give it an empty slice, so that's taken care of.

The problem is that your subprocess obviously expects you to write something, and you just don't write anything. You should decide what you want to send the subprocess as the initial input. Having the initial input empty doesn't work because nothing will get sent and your subprocess will wait for the input while you wait for its output.

It's hard to help without knowing what kind of subprocess you are starting and what communication protocol it expects. For example, shells expect commands to end with a newline or end-of-file, and your empty input includes neither. Did you just forget to include a newline in the initial input?

**Comment by martonlanga** [comment]
> I am confused by the question. write_all() already doesn't try to write if you give it an empty slice, so that's taken care of.

Sorry, misinterpreted your previous comment.

There is no initial input. [Here's a quick screencast showing what I'm trying to do.](https://www.loom.com/share/7d66ae4f92e24db9809295066921c8ca)

*Here3* is right before this line: `let len = reader.read(&mut chunk)?;`

**Comment by martonlanga** [comment]
The events are emitted on keypress. If it wasn't stuck in that loop, the message would be received and then written to stdin.

**Comment by hniksic** [comment]
Maybe you shouldn't read anything if you didn't actually write anything, i.e. if `stdin` was empty?

**Comment by martonlanga** [comment]
But I don't know whether the program I'm running wrote to stdout or not. For example running vim would write something initially to stdout and then wait for user input, but that does not mean that stdout reached the End Of File.

Going to try to spawn a new thread just for reading stdout or using tokio to read the stdout FIle async, so it doesn't block.

**Comment by hniksic** [comment]
> But I don't know whether the program I'm running wrote to stdout or not. 

I meant that you probably shouldn't read from the program if you know you haven't written anything new to it in the last iteration (because your `stdin` variable contained an empty string).

> Going to try to spawn a new thread just for reading stdout or using tokio to read the stdout FIle async, so it doesn't block.

In the long run, thaat probably makes the most sense. Reading and writing in separate threads is one of the strategies `Popen::communicate()` uses to avoid deadlocks.

If you don't mind, I'd like to close this issue because there is no issue with `subprocess` here, as far as I can tell. If you have a usage question or need advice, feel free to open a new issue or leave a comment here anyway.

**Comment by martonlanga** [comment]
> In the long run, thaat probably makes the most sense. Reading and writing in separate threads is one of the strategies Popen::communicate() uses to avoid deadlocks.

Will look into how that works then.

Sure, thanks a lot for your help!
