### ISSUE TITLE
enclosed type of ExitStatus::Signaled u8 vs. i32 / c_int?

### ISSUE THREAD

**Issue by f0rki** [hniksic/rust-subprocess#57]
I just noticed, that `ExitStatus::Signaled` contains a `u8`, which is somewhat weird, because when comparing to `libc` constants you have to cast them. i.e., I just wrote code like this and it was very intuitive.

```rust
if let ExitStatus::Signaled(signum) = *status {
  (signum as i32) == libc::SIGABRT
}
```

Please consider changing this to a `i32` in the next version.

**Comment by hniksic** [comment]
I'm a bit wary of using `i32` here because there's no guarantee that the signal numbers will be precisely `i32` (or any particular type) on all systems - and I'd like to avoid exposing the libc types.

Perhaps `ExitStatus` should provide a function to test for a particular signal:

```rust
    /// True if the subprocess was killed by a signal with the specified number.
    pub fn is_killed_by<T: Eq + From<u8>>(self, signum: T) -> bool {
        if let ExitStatus::Signaled(n) = self {
            let n: T = n.into();
            return n == signum
        }
        false
    }
```

You could then write your `if lwr` as just `status.is_killed_by(libc::SIGABRT)`.

**Comment by f0rki** [comment]
That new API is even better :) thanks!
