### ISSUE TITLE
command error doesnt get caputred in the stderr

### ISSUE THREAD

**Issue by alexzanderr** [hniksic/rust-subprocess#62]
hey. very nice crate.

im having here a very interesting situation

i have this code; just trying to run a command that is not found on my system using the `Exec::shell` and get its output and err into 2 variables:
```rust
extern crate subprocess;

use subprocess::Exec;
use subprocess::Redirection;

fn main() {
    let out_and_err = Exec::shell("not_found")
        .stdout(Redirection::Pipe)
        .stderr(Redirection::Merge)
        .capture().unwrap();

    let out = out_and_err.stdout_str(); 
    // here out is the error message from shell: 
    // "sh: line 1: not_found: command not found\n"
    println!("{:?}", out);


    
    let err = out_and_err.stderr_str();
    // println!("{:?}", out);
    println!("{:?}", err); // <---- here the error is empty string ""
}
```

when i run it i do get:
```sh
❱  cargo run --example sub
    Blocking waiting for file lock on build directory
   Compiling rust_core v0.0.1 (~/Alexzander__/programming/rust/core)
    Finished dev [unoptimized + debuginfo] target(s) in 1.10s
     Running `target/debug/examples/sub`

"sh: line 1: not_found: command not found\n"
""
```

my questions are: 
- is this the expected behavior when the shell its returning command not found error? 
- shouldnt `let err = out_and_err.stderr_str();` contain the message `sh: line 1: not_found: command not found` ?

because when im running `not_found` in my shell its exiting with code `127`:
```shell
❱  not_found
zsh: command not found: not_found

鉶(tmux)
 [~/Alexzander__/programming/rust/core]
 git:(main[-US?--UT])
✘ exit:(code[127])           <--------- here
❱

```

**Comment by hniksic** [comment]
> is this the expected behavior when the shell its returning command not found error?

That's indeed the expected behavior. `Redirection::Merge` means "redirect this stream into the other one, merging it with its content". When applied to stderr, that means "the subprocess writing to standard error will behave as if it were writing to standard output instead". If a stream is redirected away, then you cannot obtain it with `stderr_str()`.

The shell does the same thing with its `2>&1` operator, which you can check by writing a scipt like this:

```
#!/bin/bash
echo bla
no_command >error-merged 2>&1
```

Now run that script as `./script >out 2>err`, and you should notice that:

* the file `error-merged` contains the error message, because `no_command` produced nothing on stdout, and just the error message on stderr, so that was all that got written
* the file `out` contains "bla", because the script printed that to stdout
* the file `err` is empty, because the script no output (the error of running `no_command` got redirected to stdout and thence to `error-merged`)

> because when im running not_found in my shell its exiting with code 127:

The 127 exit code should be observable using the `subprocess` crate as well, by inspecting the `exit_status` field.

**Comment by alexzanderr** [comment]
thanks for response.

okey, i removed `merge`:
```rust
    let errorneous_command = "not_found";
    let out_and_err = Exec::shell(errorneous_command)
        .stdout(Redirection::Pipe)
        .stderr(Redirection::Pipe)
        .capture();

    if let Err(ref err) = out_and_err {
        println!("{:?}", err);
    }
```
i still got empty string.

**Comment by alexzanderr** [comment]
thanks for response.

okey then, i removed `merge`:
```rust
    let errorneous_command = "not_found";
    let out_and_err = Exec::shell(errorneous_command)
        .stdout(Redirection::Pipe)
        .stderr(Redirection::Pipe)
        .capture();

    println!("{:?}", out_and_err.as_ref().unwrap().stderr_str());
```
and i still got empty string

**Comment by alexzanderr** [comment]
or maybe the `stderr_str()` returns only the error message from the executed command. and in my case the command didnt even execute because it was not found in my shell.

**Comment by alexzanderr** [comment]
oooh. gotcha

i do get this output
```
"sh: line 1: not_found: command not found\n" <- this is the stdout of the shell
Exited(127)                                  <- exit code of the shell

```

and thats why i got nothing on `stderr`, because the shell its printing `nothing to stderr`, only to stdout.

**Comment by alexzanderr** [comment]
sorry for opening this issue...
i need to read more documentation.

**Comment by hniksic** [comment]
In case someone finds this via a search engine, your snippet actually produces a non-empty string for me, so something else must have been wrong.

> or maybe the `stderr_str()` returns only the error message from the executed command.

`Exec::shell()` should capture the shell's output as well (if there is any). `Exec::shell("foo bar")` is just sugar (on Unix) for `Exec::cmd("sh").arg("-c").arg("foo bar")`.
